### ISSUE TITLE
Missing 'underscore' dependency for 'vtde-word-count'

### ISSUE THREAD

**Issue by mcaskill** [sheabunge/visual-term-description-editor#11]
Hi,

In the latest version(s) of WordPress, this error arises on both `edit-tags.php` and `term.php`:

```
ReferenceError: _ is not defined
```

The `vtde-word-count` script that's enqueued should depend on `underscore` to ensure the [`wordcount.js`](js/wordcount.js) works properly.

Thanks for the plugin.

**Comment by sheabunge** [comment]
Thanks for reporting this – for some reason, it doesn't require listing as a dependency for my testing sites, but I've added it to the `wp_enqueue_script` call.
