### ISSUE TITLE
HTML Errors

### ISSUE THREAD

**Issue by ThatStevensGuy** [sheabunge/visual-term-description-editor#3]
Just some small things with the HTML output of the plugin.

render_field_edit - the description should be a paragraph instead of a span, and the table row should have class="form-field term-description-wrap".

render_field_add - the opening div tag should have class="form-field term-description-wrap".

This fixed some display issues in the latest WordPress. It's easy to see when you compare the built in HTML.

**Comment by sheabunge** [comment]
Thanks very much for pointing this out; I seem to have forgotten about this issue. I'm just about to release a new version of the plugin including these changes.
