### ISSUE TITLE
How to best reuse your plugin from mine?

### ISSUE THREAD

**Issue by garex** [sheabunge/visual-term-description-editor#4]
Hi! This is not really issue, but some kind of thoughts or proposal. I need your opinion.

The problem
-----------------

My plugin X wants your plugin Y. How to achive this?

Possible options
----------------------

* Recommendation. Add to readme or FAQ of my plugin something like: "Install plugin Y to have such and such". Or add some link in some part of my pluging admin area with same recommendation.
* Include. Just include your plugin into mine and load it if it's not installed on user WP.
* "Fork". Include your plugin but with renamed classname. And also customize as I want and etc.

Current WP dependency issue
-----------------------------------------

It's exists and possible proposals are to include some deps management into WP core.
Another solution is some standalone plugin that then can manage dependencies.

My personal wish
-----------------------

I dont' want to fork, but better reuse your plugin Y. I know, that we can improve it or add some hooks/filters where it's required. But also I know, that users are lasy, so it's better to include your plugin into mine and somehow load it if it's not in user's current WP install.

What do you think about it and/or solution for such problems?

**Comment by garex** [comment]
Plugin deps proposal
================

* !!Should be standalone plugin part — MUST not be standlaone plugin!!
* MUST not be in WP core as plugins should be compatible backward
* Could be in WP core
* Could be in two active plugins with different versions
* When two versions then somehow latest version must win and do all process of loading from two plugins
* Could be simple composer package
* Tested backward to PHP5.2  and WP3.2
* MUST load another included plugin if it's not activated already in main install OR in another plugin
* Dependent plugin installed wins
* Dependent plugin when included in two other should win with latest version
* Also should have recommendation feature when plugin recommends another plugin to install in some place (manually or as a config param) and recomendation message should be hidden after close

----------------
ps: Somthing like this is currently in my head.

**Comment by sheabunge** [comment]
Your ideas sound really great. Unfortunately, I don't think that any sort of spphisticated dependance managment will be build into core any time soon, where it really needs to be to work effectively.

Adding a recommendation in the readme might work, but in my experiance very few users actually bother to read the readme or even the WordPress.org plugins page. 

I don't have a problem with you including this plugin as part of yours. It's MIT licenced, so there should be no conflicts there. You could click the watch button at the top of this page and be notified when I make an update. However, I don't think that this is the best route to follow - it's better to have two small and efficient plugins then a combined bloted plugin.

I think that you might find the [TGM-Plugin-Activation](https://github.com/thomasgriffin/TGM-Plugin-Activation) class rather useful. It allows you to define a list of plugins that are recommended for install on plugin activation. It's really easy to set up, and provides a good experience to the end user.

Also, if you have ways that this plugin could be improved, then please don't hesitate to open an issue or submit a pull request. I would love to hear your ideas for improvments to make this plugin better :)

**Comment by garex** [comment]
@sheabunge Yea! Regarding TGM I saw it later after this issue. I think it will do that I want.

Regarding WP core I think it MUST not be in core as we need always not only latest WP/PHP but previous to work too.

Regarding this plugin I think I can add tests to it, improve some internals may be, make compatible with WP from 3.2 to latest, add autotests to travis and etc. All those infrastructure that I already have on my current wp-testing plugin. Anyway when I will send PRs. I'll break them on single independent parts.
