### ISSUE TITLE
oEmbed not working

### ISSUE THREAD

**Issue by gthayer** [sheabunge/visual-term-description-editor#6]
I'm finding that the oEmbed functionaility does not currently work. When trying to embed a YouTube video, the editor strips out the link.

Additionally, if I wrap the link with [embed][/embed], a place holder appears but the video never loads.

**Comment by gthayer** [comment]
I looked into a bit further and changed the filters to more match the_content. It still does not do the fancy oEmbed stuff, but the [embed] tags work.

https://github.com/gthayer/visual-term-description-editor/commit/ff11dceab469fab772047c1a8c192c76f007756a

**Comment by sheabunge** [comment]
Looking at [this plugin](http://plugins.svn.wordpress.org/text-widget-oembed/trunk/text-widget-oembed.php), perhaps this could be a solution?

```php
add_filter( 'term_description', array( $wp_embed, 'autoembed' ), 8 );
```

**Comment by gthayer** [comment]
That seems to work for me. The fancy JS embed isn't there, but it's good enough for my needs right now. Thanks for taking a look!
